# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0e151d3b7dfac9b1885b4bb0b6a32cc"
name = "offres-handle"
handle = "offres-handle"
application_url = "https://walked-issued-cash-commonwealth.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jokipiin-pellava-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://walked-issued-cash-commonwealth.trycloudflare.com/auth/callback",
  "https://walked-issued-cash-commonwealth.trycloudflare.com/auth/shopify/callback",
  "https://walked-issued-cash-commonwealth.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
