# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5f735b584c8757b326cdba3008bf4f4b"
name = "fetch-offers"
handle = "fetch-offers"
application_url = "https://bracelet-cambodia-roommates-gcc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jokipiin-pellava-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://bracelet-cambodia-roommates-gcc.trycloudflare.com/auth/callback",
  "https://bracelet-cambodia-roommates-gcc.trycloudflare.com/auth/shopify/callback",
  "https://bracelet-cambodia-roommates-gcc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
